@TM:1366012176
@N:  :"":0:0:0:-1|Running in logic synthesis mode without enhanced optimization
@TM:1365969178
@N:  :"":0:0:0:-1|Running in 32-bit mode
@TM:1366012312
@N: FA174 :"":0:0:0:-1|The following device usage report estimates place and route data. Please look at the place and route report for final resource usage..
@TM:1366012176
@N: MF249 :"":0:0:0:-1|Running in 64-bit mode.
@N: MF257 :"":0:0:0:-1|Gated clock conversion enabled 
@TM:1366012312
@N: MF276 :"":0:0:0:-1|Gated clock conversion enabled, but no gated clocks found in design 
@N: MF333 :"":0:0:0:-1|Generated clock conversion enabled, but no generated clocks found in design 
@TM:1366012176
@W: MO161 :"":0:0:0:-1|Register bit false_5 is always 0, optimizing ...
@W: MO161 :"":0:0:0:-1|Register bit false_4 is always 0, optimizing ...
@W: MO161 :"":0:0:0:-1|Register bit false_3 is always 0, optimizing ...
@W: MO161 :"":0:0:0:-1|Register bit false_2 is always 0, optimizing ...
@W: MO161 :"":0:0:0:-1|Register bit false_1 is always 0, optimizing ...
@W: MO161 :"":0:0:0:-1|Register bit false_0 is always 0, optimizing ...
@TM:1366016762
@W: MT116 :"":0:0:0:-1|Paths from clock (global_nets_top|clk_blk_inst.pll_new_2_inst.sdram_clk_derived_clock:r) to clock (global_nets_top|clk_blk_inst.pll_new_1_inst.system_clk_derived_clock:r) are overconstrained because the required time of 0.12 ns is too small.  
@W: MT116 :"":0:0:0:-1|Paths from clock (global_nets_top|clk_blk_inst.pll_new_1_inst.system_clk_derived_clock:r) to clock (global_nets_top|clk_blk_inst.pll_new_2_inst.sdram_clk_derived_clock:r) are overconstrained because the required time of 0.12 ns is too small.  
@TM:1366012312
@N: MT320 :"":0:0:0:-1|This timing report estimates place and route data. Please look at the place and route timing report for final timing..
@N: MT322 :"":0:0:0:-1|Clock constraints cover only FF-to-FF paths associated with the clock..
@TM:1366012176
@N: CD720 :"C:\Synopsys\fpga_D201003SP1\lib\vhd\std.vhd":123:18:123:21|M
@N: CD231 :"C:\Synopsys\fpga_D201003SP1\lib\vhd\std_logic_textio.vhd":79:15:79:16|M
@N: CD630 :"H:\Project\SG_Project\VHDL\altera_16to8_dc_ram.vhd":42:7:42:25|M
@N: CD630 :"H:\Project\SG_Project\VHDL\altera_16to8_dc_ram.vhd":62:11:62:20|M
@N: CD630 :"H:\Project\SG_Project\VHDL\altera_8to16_dc_ram.vhd":42:7:42:25|M
@N: CD630 :"H:\Project\SG_Project\VHDL\altera_8to16_dc_ram.vhd":62:11:62:20|M
@N: CD630 :"H:\Project\SG_Project\VHDL\checksum_calc.vhd":62:7:62:19|M
@W: CG296 :"H:\Project\SG_Project\VHDL\checksum_calc.vhd":120:24:120:30|M
@W: CL170 :"H:\Project\SG_Project\VHDL\checksum_calc.vhd":122:1:122:2|M
@W: CG290 :"H:\Project\SG_Project\VHDL\checksum_calc.vhd":123:15:123:31|M
@N: CD630 :"H:\Project\SG_Project\VHDL\clk_blk_top.vhd":32:7:32:17|M
@N: CD630 :"H:\Project\SG_Project\VHDL\dc_fifo.vhd":42:7:42:13|M
@N: CD630 :"H:\Project\SG_Project\VHDL\dc_fifo.vhd":68:11:68:16|M
@TM:1366012312
@W: MT246 :"h:\project\sg_project\vhdl\dc_fifo.vhd":104:1:104:16|M
@TM:1366012176
@N: CD630 :"H:\Project\SG_Project\VHDL\disp_ctrl_top.vhd":35:7:35:19|M
@W: CD638 :"H:\Project\SG_Project\VHDL\disp_ctrl_top.vhd":157:7:157:23|M
@W: CD638 :"H:\Project\SG_Project\VHDL\disp_ctrl_top.vhd":178:7:178:19|M
@W: CD638 :"H:\Project\SG_Project\VHDL\disp_ctrl_top.vhd":180:7:180:17|M
@W: CD638 :"H:\Project\SG_Project\VHDL\disp_ctrl_top.vhd":181:7:181:19|M
@W: CD638 :"H:\Project\SG_Project\VHDL\disp_ctrl_top.vhd":221:7:221:28|M
@W: CL240 :"H:\Project\SG_Project\VHDL\disp_ctrl_top.vhd":221:7:221:28|M
@W: CD638 :"H:\Project\SG_Project\VHDL\disp_ctrl_top.vhd":223:7:223:31|M
@W: CL240 :"H:\Project\SG_Project\VHDL\disp_ctrl_top.vhd":223:7:223:31|M
@W: CD638 :"H:\Project\SG_Project\VHDL\disp_ctrl_top.vhd":224:7:224:29|M
@W: CL240 :"H:\Project\SG_Project\VHDL\disp_ctrl_top.vhd":224:7:224:29|M
@W: CD638 :"H:\Project\SG_Project\VHDL\disp_ctrl_top.vhd":226:7:226:32|M
@W: CL240 :"H:\Project\SG_Project\VHDL\disp_ctrl_top.vhd":226:7:226:32|M
@W: CD638 :"H:\Project\SG_Project\VHDL\disp_ctrl_top.vhd":256:7:256:17|M
@W: CD638 :"H:\Project\SG_Project\VHDL\disp_ctrl_top.vhd":257:7:257:23|M
@W: CD638 :"H:\Project\SG_Project\VHDL\disp_ctrl_top.vhd":272:7:272:12|M
@W: CD638 :"H:\Project\SG_Project\VHDL\disp_ctrl_top.vhd":273:7:273:13|M
@W: BN132 :"h:\project\sg_project\vhdl\disp_ctrl_top.vhd":766:2:766:3|M
@W: BN132 :"h:\project\sg_project\vhdl\disp_ctrl_top.vhd":766:2:766:3|M
@W: BN132 :"h:\project\sg_project\vhdl\disp_ctrl_top.vhd":766:2:766:3|M
@W: BN132 :"h:\project\sg_project\vhdl\disp_ctrl_top.vhd":766:2:766:3|M
@W: CD326 :"H:\Project\SG_Project\VHDL\disp_ctrl_top.vhd":974:0:974:11|M
@W: CD326 :"H:\Project\SG_Project\VHDL\disp_ctrl_top.vhd":996:0:996:11|M
@W: CL168 :"H:\Project\SG_Project\VHDL\disp_ctrl_top.vhd":996:0:996:11|M
@W: CL111 :"H:\Project\SG_Project\VHDL\disp_ctrl_top.vhd":1307:1:1307:2|M
@W: CL169 :"H:\Project\SG_Project\VHDL\disp_ctrl_top.vhd":1307:1:1307:2|M
@N: CL177 :"H:\Project\SG_Project\VHDL\disp_ctrl_top.vhd":1307:1:1307:2|M
@W: CL190 :"H:\Project\SG_Project\VHDL\disp_ctrl_top.vhd":1307:1:1307:2|M
@W: CL260 :"H:\Project\SG_Project\VHDL\disp_ctrl_top.vhd":1307:1:1307:2|M
@W: CL260 :"H:\Project\SG_Project\VHDL\disp_ctrl_top.vhd":1307:1:1307:2|M
@N: CD630 :"H:\Project\SG_Project\VHDL\gen_reg.vhd":34:7:34:13|M
@N: CD630 :"H:\Project\SG_Project\VHDL\gen_reg.vhd":34:7:34:13|M
@N: CD630 :"H:\Project\SG_Project\VHDL\gen_reg.vhd":34:7:34:13|M
@N: CD630 :"H:\Project\SG_Project\VHDL\gen_reg.vhd":34:7:34:13|M
@N: CD630 :"H:\Project\SG_Project\VHDL\gen_reg.vhd":34:7:34:13|M
@N: CD630 :"H:\Project\SG_Project\VHDL\gen_reg.vhd":34:7:34:13|M
@N: CD630 :"H:\Project\SG_Project\VHDL\gen_reg.vhd":34:7:34:13|M
@N: CD630 :"H:\Project\SG_Project\VHDL\gen_reg.vhd":34:7:34:13|M
@N: CD630 :"H:\Project\SG_Project\VHDL\gen_reg.vhd":34:7:34:13|M
@N: CD630 :"H:\Project\SG_Project\VHDL\gen_reg.vhd":34:7:34:13|M
@N: CD630 :"H:\Project\SG_Project\VHDL\gen_reg.vhd":34:7:34:13|M
@N: CD630 :"H:\Project\SG_Project\VHDL\gen_reg.vhd":34:7:34:13|M
@N: CD630 :"H:\Project\SG_Project\VHDL\gen_reg.vhd":34:7:34:13|M
@N: CD630 :"H:\Project\SG_Project\VHDL\gen_reg.vhd":34:7:34:13|M
@W: CL159 :"H:\Project\SG_Project\VHDL\gen_reg.vhd":62:3:62:7|M
@N: BN116 :"h:\project\sg_project\vhdl\gen_reg.vhd":86:2:86:3|M
@N: CD364 :"H:\Project\SG_Project\VHDL\gen_reg.vhd":102:5:102:12|M
@N: CD364 :"H:\Project\SG_Project\VHDL\gen_reg.vhd":102:5:102:12|M
@N: CD364 :"H:\Project\SG_Project\VHDL\gen_reg.vhd":102:5:102:12|M
@N: CD364 :"H:\Project\SG_Project\VHDL\gen_reg.vhd":102:5:102:12|M
@N: CD364 :"H:\Project\SG_Project\VHDL\gen_reg.vhd":102:5:102:12|M
@N: CD364 :"H:\Project\SG_Project\VHDL\gen_reg.vhd":102:5:102:12|M
@N: CD364 :"H:\Project\SG_Project\VHDL\gen_reg.vhd":102:5:102:12|M
@N: CD364 :"H:\Project\SG_Project\VHDL\gen_reg.vhd":102:5:102:12|M
@N: CD364 :"H:\Project\SG_Project\VHDL\gen_reg.vhd":102:5:102:12|M
@N: CD364 :"H:\Project\SG_Project\VHDL\gen_reg.vhd":102:5:102:12|M
@N: CD364 :"H:\Project\SG_Project\VHDL\gen_reg.vhd":102:5:102:12|M
@N: CD364 :"H:\Project\SG_Project\VHDL\gen_reg.vhd":102:5:102:12|M
@N: CD364 :"H:\Project\SG_Project\VHDL\gen_reg.vhd":102:5:102:12|M
@N: CD364 :"H:\Project\SG_Project\VHDL\gen_reg.vhd":102:5:102:12|M
@N: CD364 :"H:\Project\SG_Project\VHDL\gen_reg.vhd":106:4:106:11|M
@N: CD364 :"H:\Project\SG_Project\VHDL\gen_reg.vhd":106:4:106:11|M
@N: CD364 :"H:\Project\SG_Project\VHDL\gen_reg.vhd":106:4:106:11|M
@N: CD364 :"H:\Project\SG_Project\VHDL\gen_reg.vhd":106:4:106:11|M
@N: CD364 :"H:\Project\SG_Project\VHDL\gen_reg.vhd":106:4:106:11|M
@N: CD364 :"H:\Project\SG_Project\VHDL\gen_reg.vhd":106:4:106:11|M
@N: CD364 :"H:\Project\SG_Project\VHDL\gen_reg.vhd":106:4:106:11|M
@N: CD364 :"H:\Project\SG_Project\VHDL\gen_reg.vhd":106:4:106:11|M
@N: CD364 :"H:\Project\SG_Project\VHDL\gen_reg.vhd":106:4:106:11|M
@N: CD364 :"H:\Project\SG_Project\VHDL\gen_reg.vhd":106:4:106:11|M
@N: CD364 :"H:\Project\SG_Project\VHDL\gen_reg.vhd":106:4:106:11|M
@N: CD364 :"H:\Project\SG_Project\VHDL\gen_reg.vhd":106:4:106:11|M
@N: CD364 :"H:\Project\SG_Project\VHDL\gen_reg.vhd":106:4:106:11|M
@N: CD364 :"H:\Project\SG_Project\VHDL\gen_reg.vhd":106:4:106:11|M
@N: CD630 :"H:\Project\SG_Project\VHDL\global_nets_top.vhd":37:7:37:21|M
@N: CD630 :"H:\Project\SG_Project\VHDL\Hexss.vhd":23:7:23:11|M
@N: FA239 :"h:\project\sg_project\vhdl\hexss.vhd":48:3:48:11|M
@N: CD630 :"H:\Project\SG_Project\VHDL\intercon.vhd":35:7:35:14|M
@N: CD630 :"H:\Project\SG_Project\VHDL\intercon.vhd":35:7:35:14|M
@N: CD233 :"H:\Project\SG_Project\VHDL\intercon.vhd":98:22:98:23|M
@N: CD233 :"H:\Project\SG_Project\VHDL\intercon.vhd":98:22:98:23|M
@W: CL138 :"H:\Project\SG_Project\VHDL\intercon.vhd":167:2:167:3|M
@N: CD364 :"H:\Project\SG_Project\VHDL\intercon.vhd":175:6:175:12|M
@N: CD364 :"H:\Project\SG_Project\VHDL\intercon.vhd":175:6:175:12|M
@N: CD364 :"H:\Project\SG_Project\VHDL\intercon.vhd":184:6:184:11|M
@N: CD364 :"H:\Project\SG_Project\VHDL\intercon.vhd":184:6:184:11|M
@N: CD364 :"H:\Project\SG_Project\VHDL\intercon.vhd":191:5:191:11|M
@N: CD364 :"H:\Project\SG_Project\VHDL\intercon.vhd":191:5:191:11|M
@N: CD364 :"H:\Project\SG_Project\VHDL\intercon.vhd":192:5:192:11|M
@N: CD364 :"H:\Project\SG_Project\VHDL\intercon.vhd":192:5:192:11|M
@W: CD604 :"H:\Project\SG_Project\VHDL\intercon.vhd":194:4:194:19|M
@W: CD604 :"H:\Project\SG_Project\VHDL\intercon.vhd":194:4:194:19|M
@N: CD630 :"H:\Project\SG_Project\VHDL\intercon_mux.vhd":24:7:24:18|M
@N: CD630 :"H:\Project\SG_Project\VHDL\mds_top.vhd":31:7:31:13|M
@N: CD630 :"H:\Project\SG_Project\VHDL\mem_ctrl_rd.vhd":36:7:36:17|M
@N: BN116 :"h:\project\sg_project\vhdl\mem_ctrl_rd.vhd":382:2:382:3|M
@N: CL135 :"H:\Project\SG_Project\VHDL\mem_ctrl_rd.vhd":382:2:382:3|M
@W: CL169 :"H:\Project\SG_Project\VHDL\mem_ctrl_rd.vhd":382:2:382:3|M
@N: CL135 :"H:\Project\SG_Project\VHDL\mem_ctrl_rd.vhd":456:2:456:3|M
@N: CD630 :"H:\Project\SG_Project\VHDL\mem_ctrl_rd_wbm.vhd":35:7:35:21|M
@W: CL246 :"H:\Project\SG_Project\VHDL\mem_ctrl_rd_wbm.vhd":80:2:80:9|M
@N: CD231 :"H:\Project\SG_Project\VHDL\mem_ctrl_rd_wbm.vhd":97:17:97:18|M
@N:  :"h:\project\sg_project\vhdl\mem_ctrl_rd_wbm.vhd":188:2:188:3|M
@N:  :"h:\project\sg_project\vhdl\mem_ctrl_rd_wbm.vhd":188:2:188:3|M
@N:  :"h:\project\sg_project\vhdl\mem_ctrl_rd_wbm.vhd":188:2:188:3|M
@N: CL201 :"H:\Project\SG_Project\VHDL\mem_ctrl_rd_wbm.vhd":188:2:188:3|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_rd_wbm.vhd":219:7:219:17|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_rd_wbm.vhd":226:6:226:16|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_rd_wbm.vhd":231:5:231:18|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_rd_wbm.vhd":232:5:232:15|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_rd_wbm.vhd":233:5:233:17|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_rd_wbm.vhd":266:6:266:18|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_rd_wbm.vhd":267:6:267:18|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_rd_wbm.vhd":268:6:268:16|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_rd_wbm.vhd":279:6:279:18|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_rd_wbm.vhd":284:7:284:20|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_rd_wbm.vhd":298:8:298:20|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_rd_wbm.vhd":308:7:308:19|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_rd_wbm.vhd":309:7:309:17|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_rd_wbm.vhd":310:7:310:20|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_rd_wbm.vhd":311:7:311:19|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_rd_wbm.vhd":317:5:317:15|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_rd_wbm.vhd":318:5:318:18|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_rd_wbm.vhd":323:6:323:18|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_rd_wbm.vhd":347:6:347:21|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_rd_wbm.vhd":386:5:386:18|M
@W: CD604 :"H:\Project\SG_Project\VHDL\mem_ctrl_rd_wbm.vhd":394:4:394:17|M
@N:  :"h:\project\sg_project\vhdl\mem_ctrl_rd_wbm.vhd":409:2:409:3|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_rd_wbm.vhd":419:4:419:11|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_rd_wbm.vhd":473:4:473:12|M
@W: FA160 :"h:\project\sg_project\vhdl\mem_ctrl_rd_wbm.vhd":486:2:486:3|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_rd_wbm.vhd":492:4:492:9|M
@N:  :"h:\project\sg_project\vhdl\mem_ctrl_rd_wbm.vhd":522:2:522:3|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_rd_wbm.vhd":530:5:530:17|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_rd_wbm.vhd":594:4:594:16|M
@N:  :"h:\project\sg_project\vhdl\mem_ctrl_rd_wbm.vhd":625:2:625:3|M
@N: CD630 :"H:\Project\SG_Project\VHDL\mem_ctrl_rd_wbs.vhd":37:7:37:21|M
@W: CL247 :"H:\Project\SG_Project\VHDL\mem_ctrl_rd_wbs.vhd":49:2:49:10|M
@N: CD231 :"H:\Project\SG_Project\VHDL\mem_ctrl_rd_wbs.vhd":83:17:83:18|M
@N: CL201 :"H:\Project\SG_Project\VHDL\mem_ctrl_rd_wbs.vhd":136:2:136:3|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_rd_wbs.vhd":149:7:149:16|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_rd_wbs.vhd":152:6:152:15|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_rd_wbs.vhd":171:6:171:15|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_rd_wbs.vhd":188:7:188:16|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_rd_wbs.vhd":196:6:196:15|M
@W: CD604 :"H:\Project\SG_Project\VHDL\mem_ctrl_rd_wbs.vhd":204:4:204:17|M
@N:  :"h:\project\sg_project\vhdl\mem_ctrl_rd_wbs.vhd":300:2:300:3|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_rd_wbs.vhd":309:5:309:18|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_rd_wbs.vhd":314:4:314:17|M
@N: BN116 :"h:\project\sg_project\vhdl\mem_ctrl_rd_wbs.vhd":384:2:384:3|M
@N: CD630 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr.vhd":41:7:41:17|M
@N: BN116 :"h:\project\sg_project\vhdl\mem_ctrl_wr.vhd":355:2:355:3|M
@W: CL111 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr.vhd":355:2:355:3|M
@N: CL135 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr.vhd":355:2:355:3|M
@W: CL170 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr.vhd":355:2:355:3|M
@N: CD630 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbm.vhd":34:7:34:21|M
@W: CL246 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbm.vhd":68:2:68:9|M
@N: CD231 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbm.vhd":93:17:93:18|M
@N:  :"h:\project\sg_project\vhdl\mem_ctrl_wr_wbm.vhd":187:2:187:3|M
@N:  :"h:\project\sg_project\vhdl\mem_ctrl_wr_wbm.vhd":187:2:187:3|M
@N: CL201 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbm.vhd":187:2:187:3|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbm.vhd":217:8:217:18|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbm.vhd":224:7:224:17|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbm.vhd":228:6:228:16|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbm.vhd":233:5:233:18|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbm.vhd":235:5:235:15|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbm.vhd":255:6:255:19|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbm.vhd":256:6:256:18|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbm.vhd":257:6:257:16|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbm.vhd":265:6:265:19|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbm.vhd":266:6:266:18|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbm.vhd":271:7:271:20|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbm.vhd":272:7:272:20|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbm.vhd":275:7:275:22|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbm.vhd":296:7:296:20|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbm.vhd":297:7:297:17|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbm.vhd":298:7:298:20|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbm.vhd":299:7:299:19|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbm.vhd":305:5:305:18|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbm.vhd":306:5:306:15|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbm.vhd":307:5:307:18|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbm.vhd":319:6:319:21|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbm.vhd":347:5:347:15|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbm.vhd":349:5:349:18|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbm.vhd":358:5:358:15|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbm.vhd":359:5:359:18|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbm.vhd":362:6:362:19|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbm.vhd":368:6:368:18|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbm.vhd":371:6:371:18|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbm.vhd":385:5:385:18|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbm.vhd":387:5:387:15|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbm.vhd":395:5:395:18|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbm.vhd":397:5:397:15|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbm.vhd":408:5:408:18|M
@W: CD604 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbm.vhd":415:4:415:17|M
@N: CL177 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbm.vhd":459:2:459:3|M
@W: FA160 :"h:\project\sg_project\vhdl\mem_ctrl_wr_wbm.vhd":459:2:459:3|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbm.vhd":471:4:471:15|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbm.vhd":514:5:514:16|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbm.vhd":518:4:518:15|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbm.vhd":525:6:525:17|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbm.vhd":528:5:528:16|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbm.vhd":536:4:536:15|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbm.vhd":537:4:537:15|M
@N:  :"h:\project\sg_project\vhdl\mem_ctrl_wr_wbm.vhd":550:2:550:3|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbm.vhd":574:4:574:12|M
@N:  :"h:\project\sg_project\vhdl\mem_ctrl_wr_wbm.vhd":588:2:588:3|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbm.vhd":597:4:597:9|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbm.vhd":645:4:645:13|M
@N: CD630 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbs.vhd":25:7:25:21|M
@W: CL247 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbs.vhd":37:2:37:10|M
@N: CD231 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbs.vhd":67:17:67:18|M
@N:  :"h:\project\sg_project\vhdl\mem_ctrl_wr_wbs.vhd":119:2:119:3|M
@N: CL201 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbs.vhd":119:2:119:3|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbs.vhd":131:5:131:18|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbs.vhd":159:7:159:20|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbs.vhd":176:6:176:19|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbs.vhd":181:5:181:18|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbs.vhd":200:6:200:15|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbs.vhd":205:5:205:18|M
@W: CD604 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbs.vhd":207:4:207:17|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbs.vhd":228:4:228:14|M
@N:  :"h:\project\sg_project\vhdl\mem_ctrl_wr_wbs.vhd":298:2:298:3|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_ctrl_wr_wbs.vhd":306:4:306:11|M
@N: BN116 :"h:\project\sg_project\vhdl\mem_ctrl_wr_wbs.vhd":318:2:318:3|M
@N: BN116 :"h:\project\sg_project\vhdl\mem_ctrl_wr_wbs.vhd":318:2:318:3|M
@N: CD630 :"H:\Project\SG_Project\VHDL\mem_mng_arbiter.vhd":30:7:30:21|M
@N: CD630 :"H:\Project\SG_Project\VHDL\mem_mng_top.vhd":29:7:29:17|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_mng_top.vhd":505:4:505:14|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mem_mng_top.vhd":506:4:506:14|M
@N: CD630 :"H:\Project\SG_Project\VHDL\mp_dec.vhd":52:7:52:12|M
@N: CD231 :"H:\Project\SG_Project\VHDL\mp_dec.vhd":108:19:108:20|M
@W: CD638 :"H:\Project\SG_Project\VHDL\mp_dec.vhd":152:7:152:12|M
@W: CD638 :"H:\Project\SG_Project\VHDL\mp_dec.vhd":153:7:153:16|M
@N: BN116 :"h:\project\sg_project\vhdl\mp_dec.vhd":180:2:180:3|M
@N: CL201 :"H:\Project\SG_Project\VHDL\mp_dec.vhd":180:2:180:3|M
@W: CD604 :"H:\Project\SG_Project\VHDL\mp_dec.vhd":310:5:310:18|M
@W: BN132 :"h:\project\sg_project\vhdl\mp_dec.vhd":328:2:328:3|M
@W: CL190 :"H:\Project\SG_Project\VHDL\mp_dec.vhd":328:2:328:3|M
@W: CL260 :"H:\Project\SG_Project\VHDL\mp_dec.vhd":328:2:328:3|M
@W: CL260 :"H:\Project\SG_Project\VHDL\mp_dec.vhd":328:2:328:3|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mp_dec.vhd":337:5:337:11|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mp_dec.vhd":340:4:340:10|M
@N: BN116 :"h:\project\sg_project\vhdl\mp_dec.vhd":353:2:353:3|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mp_dec.vhd":445:4:445:12|M
@N: BN116 :"h:\project\sg_project\vhdl\mp_dec.vhd":459:2:459:3|M
@N: CD630 :"H:\Project\SG_Project\VHDL\mp_enc.vhd":44:7:44:12|M
@N: CD231 :"H:\Project\SG_Project\VHDL\mp_enc.vhd":101:23:101:24|M
@W: BN132 :"h:\project\sg_project\vhdl\mp_enc.vhd":174:2:174:3|M
@W: CL190 :"H:\Project\SG_Project\VHDL\mp_enc.vhd":174:2:174:3|M
@N: CL201 :"H:\Project\SG_Project\VHDL\mp_enc.vhd":174:2:174:3|M
@W: CL260 :"H:\Project\SG_Project\VHDL\mp_enc.vhd":174:2:174:3|M
@W: CL260 :"H:\Project\SG_Project\VHDL\mp_enc.vhd":174:2:174:3|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mp_enc.vhd":327:7:327:12|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mp_enc.vhd":329:7:329:16|M
@W: CD604 :"H:\Project\SG_Project\VHDL\mp_enc.vhd":377:5:377:18|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mp_enc.vhd":384:4:384:9|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mp_enc.vhd":386:4:386:13|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mp_enc.vhd":387:4:387:10|M
@N: BN116 :"h:\project\sg_project\vhdl\mp_enc.vhd":400:2:400:3|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mp_enc.vhd":450:5:450:11|M
@N: CD364 :"H:\Project\SG_Project\VHDL\mp_enc.vhd":451:5:451:13|M
@N: CD630 :"H:\Project\SG_Project\VHDL\pixel_mng.vhd":30:7:30:15|M
@W: CL159 :"H:\Project\SG_Project\VHDL\pixel_mng.vhd":49:2:49:10|M
@W: CL159 :"H:\Project\SG_Project\VHDL\pixel_mng.vhd":61:2:61:9|M
@N: CD231 :"H:\Project\SG_Project\VHDL\pixel_mng.vhd":77:17:77:18|M
@N: BN116 :"h:\project\sg_project\vhdl\pixel_mng.vhd":158:2:158:3|M
@N: BN116 :"h:\project\sg_project\vhdl\pixel_mng.vhd":158:2:158:3|M
@W: BN132 :"h:\project\sg_project\vhdl\pixel_mng.vhd":181:2:181:3|M
@W: BN132 :"h:\project\sg_project\vhdl\pixel_mng.vhd":181:2:181:3|M
@N: CL135 :"H:\Project\SG_Project\VHDL\pixel_mng.vhd":181:2:181:3|M
@N: BN116 :"h:\project\sg_project\vhdl\pixel_mng.vhd":202:2:202:3|M
@N: BN116 :"h:\project\sg_project\vhdl\pixel_mng.vhd":216:2:216:3|M
@N: CL201 :"H:\Project\SG_Project\VHDL\pixel_mng.vhd":216:2:216:3|M
@N: BN116 :"h:\project\sg_project\vhdl\pixel_mng.vhd":223:4:223:22|M
@N: CD364 :"H:\Project\SG_Project\VHDL\pixel_mng.vhd":237:6:237:11|M
@N: BN116 :"h:\project\sg_project\vhdl\pixel_mng.vhd":243:4:243:25|M
@N: BN116 :"h:\project\sg_project\vhdl\pixel_mng.vhd":252:4:252:20|M
@N: CD364 :"H:\Project\SG_Project\VHDL\pixel_mng.vhd":264:7:264:12|M
@N: CD364 :"H:\Project\SG_Project\VHDL\pixel_mng.vhd":280:6:280:11|M
@W: MO161 :"h:\project\sg_project\vhdl\pixel_mng.vhd":283:4:283:21|M
@N: CD364 :"H:\Project\SG_Project\VHDL\pixel_mng.vhd":298:6:298:11|M
@N: BN116 :"h:\project\sg_project\vhdl\pixel_mng.vhd":302:4:302:24|M
@N: BN116 :"h:\project\sg_project\vhdl\pixel_mng.vhd":308:4:308:26|M
@N: CD364 :"H:\Project\SG_Project\VHDL\pixel_mng.vhd":318:6:318:11|M
@W: CD604 :"H:\Project\SG_Project\VHDL\pixel_mng.vhd":321:4:321:17|M
@W: MO161 :"h:\project\sg_project\vhdl\pixel_mng.vhd":335:2:335:3|M
@N: CD364 :"H:\Project\SG_Project\VHDL\pixel_mng.vhd":345:5:345:15|M
@N: CD364 :"H:\Project\SG_Project\VHDL\pixel_mng.vhd":349:4:349:14|M
@N: BN116 :"h:\project\sg_project\vhdl\pixel_mng.vhd":361:2:361:3|M
@W: MO161 :"h:\project\sg_project\vhdl\pixel_mng.vhd":361:2:361:3|M
@N: CD364 :"H:\Project\SG_Project\VHDL\pixel_mng.vhd":370:4:370:10|M
@N: CD364 :"H:\Project\SG_Project\VHDL\pixel_mng.vhd":375:5:375:15|M
@N: CD364 :"H:\Project\SG_Project\VHDL\pixel_mng.vhd":380:4:380:14|M
@N: CD364 :"H:\Project\SG_Project\VHDL\pixel_mng.vhd":385:5:385:11|M
@N: CD364 :"H:\Project\SG_Project\VHDL\pixel_mng.vhd":390:4:390:14|M
@N: CD364 :"H:\Project\SG_Project\VHDL\pixel_mng.vhd":395:5:395:11|M
@N: CD364 :"H:\Project\SG_Project\VHDL\pixel_mng.vhd":399:4:399:10|M
@N: CD364 :"H:\Project\SG_Project\VHDL\pixel_mng.vhd":400:4:400:14|M
@N:  :"h:\project\sg_project\vhdl\pixel_mng.vhd":412:2:412:3|M
@N: CD364 :"H:\Project\SG_Project\VHDL\pixel_mng.vhd":421:5:421:10|M
@N: CD364 :"H:\Project\SG_Project\VHDL\pixel_mng.vhd":427:4:427:9|M
@N: BN116 :"h:\project\sg_project\vhdl\pixel_mng.vhd":439:2:439:3|M
@N: BN116 :"h:\project\sg_project\vhdl\pixel_mng.vhd":453:2:453:3|M
@N: BN116 :"h:\project\sg_project\vhdl\pixel_mng.vhd":467:2:467:3|M
@N: CD364 :"H:\Project\SG_Project\VHDL\pixel_mng.vhd":473:4:473:14|M
@TM:1366016634
@N: CD630 :"H:\Project\SG_Project\VHDL\pll_new_1.vhd":42:7:42:15|M
@N: CD630 :"H:\Project\SG_Project\VHDL\pll_new_1.vhd":66:11:66:16|M
@N: CD630 :"H:\Project\SG_Project\VHDL\pll_new_2.vhd":42:7:42:15|M
@N: CD630 :"H:\Project\SG_Project\VHDL\pll_new_2.vhd":64:11:64:16|M
@N: CD630 :"H:\Project\SG_Project\VHDL\ram_simple.vhd":45:7:45:16|M
@N: CL134 :"H:\Project\SG_Project\VHDL\ram_simple.vhd":69:7:69:14|M
@TM:1366016762
@W: MF244 :"h:\project\sg_project\vhdl\ram_simple.vhd":69:7:69:14|M
@W: MF245 :"h:\project\sg_project\vhdl\ram_simple.vhd":69:7:69:14|M
@W: BN132 :"h:\project\sg_project\vhdl\ram_simple.vhd":98:2:98:3|M
@N: BN116 :"h:\project\sg_project\vhdl\ram_simple.vhd":113:2:113:3|M
@TM:1366016634
@N: CD630 :"H:\Project\SG_Project\VHDL\reset_blk_top.vhd":38:7:38:19|M
@N: CD630 :"H:\Project\SG_Project\VHDL\reset_debouncer.vhd":30:7:30:21|M
@N: CD364 :"H:\Project\SG_Project\VHDL\reset_debouncer.vhd":87:4:87:11|M
@N: CD364 :"H:\Project\SG_Project\VHDL\reset_debouncer.vhd":109:4:109:9|M
@N: CD630 :"H:\Project\SG_Project\VHDL\rx_path.vhd":26:7:26:13|M
@W: CL159 :"H:\Project\SG_Project\VHDL\rx_path.vhd":67:4:67:12|M
@N: CD231 :"H:\Project\SG_Project\VHDL\rx_path.vhd":82:16:82:17|M
@W: CD326 :"H:\Project\SG_Project\VHDL\rx_path.vhd":270:1:270:9|M
@TM:1366016762
@N:  :"h:\project\sg_project\vhdl\rx_path.vhd":420:2:420:3|M
@N:  :"h:\project\sg_project\vhdl\rx_path.vhd":420:2:420:3|M
@N: BN116 :"h:\project\sg_project\vhdl\rx_path.vhd":420:2:420:3|M
@TM:1366016634
@N: CL201 :"H:\Project\SG_Project\VHDL\rx_path.vhd":420:2:420:3|M
@N: CD364 :"H:\Project\SG_Project\VHDL\rx_path.vhd":457:5:457:18|M
@N: CD364 :"H:\Project\SG_Project\VHDL\rx_path.vhd":466:6:466:21|M
@N: CD364 :"H:\Project\SG_Project\VHDL\rx_path.vhd":472:7:472:18|M
@N: CD364 :"H:\Project\SG_Project\VHDL\rx_path.vhd":473:7:473:22|M
@N: CD364 :"H:\Project\SG_Project\VHDL\rx_path.vhd":474:7:474:20|M
@N: CD364 :"H:\Project\SG_Project\VHDL\rx_path.vhd":481:7:481:18|M
@N: CD364 :"H:\Project\SG_Project\VHDL\rx_path.vhd":487:6:487:17|M
@N: CD364 :"H:\Project\SG_Project\VHDL\rx_path.vhd":488:6:488:21|M
@N: CD364 :"H:\Project\SG_Project\VHDL\rx_path.vhd":490:6:490:15|M
@N: CD364 :"H:\Project\SG_Project\VHDL\rx_path.vhd":494:5:494:20|M
@N: CD364 :"H:\Project\SG_Project\VHDL\rx_path.vhd":495:5:495:16|M
@N: CD364 :"H:\Project\SG_Project\VHDL\rx_path.vhd":496:5:496:18|M
@N: CD364 :"H:\Project\SG_Project\VHDL\rx_path.vhd":500:6:500:21|M
@N: CD364 :"H:\Project\SG_Project\VHDL\rx_path.vhd":519:5:519:20|M
@N: CD364 :"H:\Project\SG_Project\VHDL\rx_path.vhd":526:6:526:20|M
@N: CD364 :"H:\Project\SG_Project\VHDL\rx_path.vhd":527:6:527:15|M
@N: CD364 :"H:\Project\SG_Project\VHDL\rx_path.vhd":535:6:535:21|M
@N: CD364 :"H:\Project\SG_Project\VHDL\rx_path.vhd":548:6:548:21|M
@N: CD364 :"H:\Project\SG_Project\VHDL\rx_path.vhd":549:6:549:15|M
@W: CD604 :"H:\Project\SG_Project\VHDL\rx_path.vhd":552:4:552:17|M
@N: CD364 :"H:\Project\SG_Project\VHDL\rx_path.vhd":578:4:578:15|M
@N: CD364 :"H:\Project\SG_Project\VHDL\rx_path.vhd":582:5:582:16|M
@N: CD364 :"H:\Project\SG_Project\VHDL\rx_path.vhd":586:4:586:15|M
@N: CD364 :"H:\Project\SG_Project\VHDL\rx_path.vhd":587:4:587:15|M
@N: CD364 :"H:\Project\SG_Project\VHDL\rx_path.vhd":617:4:617:12|M
@N: CD630 :"H:\Project\SG_Project\VHDL\sdram_controller.vhd":42:7:42:22|M
@N: CD231 :"H:\Project\SG_Project\VHDL\sdram_controller.vhd":116:18:116:19|M
@N: CD231 :"H:\Project\SG_Project\VHDL\sdram_controller.vhd":127:18:127:19|M
@TM:1366016762
@N:  :"h:\project\sg_project\vhdl\sdram_controller.vhd":224:1:224:2|M
@N:  :"h:\project\sg_project\vhdl\sdram_controller.vhd":224:1:224:2|M
@N:  :"h:\project\sg_project\vhdl\sdram_controller.vhd":224:1:224:2|M
@N:  :"h:\project\sg_project\vhdl\sdram_controller.vhd":296:1:296:2|M
@TM:1366016634
@N: CD364 :"H:\Project\SG_Project\VHDL\sdram_controller.vhd":456:4:456:12|M
@N: CD364 :"H:\Project\SG_Project\VHDL\sdram_controller.vhd":559:3:559:16|M
@N: CD364 :"H:\Project\SG_Project\VHDL\sdram_controller.vhd":592:4:592:12|M
@N: CD364 :"H:\Project\SG_Project\VHDL\sdram_controller.vhd":597:4:597:12|M
@N: CD364 :"H:\Project\SG_Project\VHDL\sdram_controller.vhd":603:4:603:12|M
@N: CD364 :"H:\Project\SG_Project\VHDL\sdram_controller.vhd":633:4:633:14|M
@TM:1366016762
@W: BN132 :"h:\project\sg_project\vhdl\sdram_controller.vhd":642:1:642:2|M
@TM:1366016634
@N: CD630 :"H:\Project\SG_Project\VHDL\SG\general_fifo.vhd":61:7:61:18|M
@N: CD630 :"H:\Project\SG_Project\VHDL\SG\general_fifo.vhd":61:7:61:18|M
@N: CD630 :"H:\Project\SG_Project\VHDL\SG\general_fifo.vhd":61:7:61:18|M
@N: CD630 :"H:\Project\SG_Project\VHDL\SG\general_fifo.vhd":61:7:61:18|M
@N: CL134 :"H:\Project\SG_Project\VHDL\SG\general_fifo.vhd":96:7:96:9|M
@N: CL134 :"H:\Project\SG_Project\VHDL\SG\general_fifo.vhd":96:7:96:9|M
@N: CL134 :"H:\Project\SG_Project\VHDL\SG\general_fifo.vhd":96:7:96:9|M
@N: CL134 :"H:\Project\SG_Project\VHDL\SG\general_fifo.vhd":96:7:96:9|M
@TM:1366016762
@W: MF244 :"h:\project\sg_project\vhdl\sg\general_fifo.vhd":96:7:96:9|M
@W: MF244 :"h:\project\sg_project\vhdl\sg\general_fifo.vhd":96:7:96:9|M
@W: MF244 :"h:\project\sg_project\vhdl\sg\general_fifo.vhd":96:7:96:9|M
@W: MF244 :"h:\project\sg_project\vhdl\sg\general_fifo.vhd":96:7:96:9|M
@W: MF245 :"h:\project\sg_project\vhdl\sg\general_fifo.vhd":96:7:96:9|M
@W: MF245 :"h:\project\sg_project\vhdl\sg\general_fifo.vhd":96:7:96:9|M
@W: MF245 :"h:\project\sg_project\vhdl\sg\general_fifo.vhd":96:7:96:9|M
@W: MF245 :"h:\project\sg_project\vhdl\sg\general_fifo.vhd":96:7:96:9|M
@N: BN116 :"h:\project\sg_project\vhdl\sg\general_fifo.vhd":116:2:116:3|M
@TM:1366016634
@N: CL177 :"H:\Project\SG_Project\VHDL\SG\general_fifo.vhd":136:2:136:3|M
@N: CL177 :"H:\Project\SG_Project\VHDL\SG\general_fifo.vhd":136:2:136:3|M
@N: CL177 :"H:\Project\SG_Project\VHDL\SG\general_fifo.vhd":136:2:136:3|M
@N: CL177 :"H:\Project\SG_Project\VHDL\SG\general_fifo.vhd":136:2:136:3|M
@TM:1366016762
@N: BN116 :"h:\project\sg_project\vhdl\sg\general_fifo.vhd":182:2:182:3|M
@N:  :"h:\project\sg_project\vhdl\sg\general_fifo.vhd":198:2:198:3|M
@N:  :"h:\project\sg_project\vhdl\sg\general_fifo.vhd":198:2:198:3|M
@N:  :"h:\project\sg_project\vhdl\sg\general_fifo.vhd":198:2:198:3|M
@N:  :"h:\project\sg_project\vhdl\sg\general_fifo.vhd":198:2:198:3|M
@N:  :"h:\project\sg_project\vhdl\sg\general_fifo.vhd":198:2:198:3|M
@N:  :"h:\project\sg_project\vhdl\sg\general_fifo.vhd":198:2:198:3|M
@N:  :"h:\project\sg_project\vhdl\sg\general_fifo.vhd":198:2:198:3|M
@N:  :"h:\project\sg_project\vhdl\sg\general_fifo.vhd":235:2:235:3|M
@N:  :"h:\project\sg_project\vhdl\sg\general_fifo.vhd":235:2:235:3|M
@N:  :"h:\project\sg_project\vhdl\sg\general_fifo.vhd":235:2:235:3|M
@N:  :"h:\project\sg_project\vhdl\sg\general_fifo.vhd":235:2:235:3|M
@TM:1366016634
@N: CD364 :"H:\Project\SG_Project\VHDL\SG\general_fifo.vhd":245:6:245:10|M
@N: CD364 :"H:\Project\SG_Project\VHDL\SG\general_fifo.vhd":245:6:245:10|M
@N: CD364 :"H:\Project\SG_Project\VHDL\SG\general_fifo.vhd":245:6:245:10|M
@N: CD364 :"H:\Project\SG_Project\VHDL\SG\general_fifo.vhd":245:6:245:10|M
@N: CD630 :"H:\Project\SG_Project\VHDL\SG\led.vhd":26:7:26:9|M
@TM:1366016762
@N:  :"h:\project\sg_project\vhdl\sg\led.vhd":62:2:62:3|M
@TM:1366016634
@N: CD630 :"H:\Project\SG_Project\VHDL\SG\manager.vhd":45:7:45:13|M
@N: CD231 :"H:\Project\SG_Project\VHDL\SG\manager.vhd":108:14:108:15|M
@W: CL169 :"H:\Project\SG_Project\VHDL\SG\manager.vhd":164:2:164:3|M
@N: CL201 :"H:\Project\SG_Project\VHDL\SG\manager.vhd":235:2:235:3|M
@W: CD604 :"H:\Project\SG_Project\VHDL\SG\manager.vhd":331:4:331:17|M
@TM:1366016762
@N:  :"h:\project\sg_project\vhdl\sg\manager.vhd":361:2:361:3|M
@N:  :"h:\project\sg_project\vhdl\sg\manager.vhd":361:2:361:3|M
@N:  :"h:\project\sg_project\vhdl\sg\manager.vhd":394:2:394:3|M
@TM:1366016634
@W: CL169 :"H:\Project\SG_Project\VHDL\SG\manager.vhd":447:2:447:3|M
@W: CL189 :"H:\Project\SG_Project\VHDL\SG\manager.vhd":447:2:447:3|M
@W: CL190 :"H:\Project\SG_Project\VHDL\SG\manager.vhd":447:2:447:3|M
@W: CL260 :"H:\Project\SG_Project\VHDL\SG\manager.vhd":447:2:447:3|M
@W: CL260 :"H:\Project\SG_Project\VHDL\SG\manager.vhd":447:2:447:3|M
@N: CD630 :"H:\Project\SG_Project\VHDL\SG\mux2.vhd":30:7:30:10|M
@N: CD630 :"H:\Project\SG_Project\VHDL\SG\opcode_store.vhd":33:7:33:18|M
@W: CL159 :"H:\Project\SG_Project\VHDL\SG\opcode_store.vhd":37:4:37:9|M
@TM:1366016762
@W: BN132 :"h:\project\sg_project\vhdl\sg\opcode_store.vhd":138:2:138:3|M
@TM:1366016634
@W: CL169 :"H:\Project\SG_Project\VHDL\SG\opcode_store.vhd":183:2:183:3|M
@TM:1366016762
@N:  :"h:\project\sg_project\vhdl\sg\opcode_store.vhd":203:2:203:3|M
@TM:1366016634
@N: CD630 :"H:\Project\SG_Project\VHDL\SG\opcode_unite.vhd":37:7:37:18|M
@N: CD233 :"H:\Project\SG_Project\VHDL\SG\opcode_unite.vhd":64:14:64:15|M
@W: CL169 :"H:\Project\SG_Project\VHDL\SG\opcode_unite.vhd":96:2:96:3|M
@N: CL201 :"H:\Project\SG_Project\VHDL\SG\opcode_unite.vhd":96:2:96:3|M
@W: CD604 :"H:\Project\SG_Project\VHDL\SG\opcode_unite.vhd":151:6:151:19|M
@N: CD630 :"H:\Project\SG_Project\VHDL\SG\RAM_300.vhd":40:7:40:13|M
@N: CL134 :"H:\Project\SG_Project\VHDL\SG\RAM_300.vhd":56:9:56:11|M
@TM:1366016762
@W: BN132 :"h:\project\sg_project\vhdl\sg\ram_300.vhd":88:2:88:3|M
@TM:1366016634
@N: CD630 :"H:\Project\SG_Project\VHDL\SG\SG_WBM_IF.vhd":30:7:30:15|M
@N: CD231 :"H:\Project\SG_Project\VHDL\SG\SG_WBM_IF.vhd":74:17:74:18|M
@N: CD364 :"H:\Project\SG_Project\VHDL\SG\SG_WBM_IF.vhd":118:4:118:12|M
@TM:1366016762
@W: BN132 :"h:\project\sg_project\vhdl\sg\sg_wbm_if.vhd":163:2:163:3|M
@TM:1366016634
@W: CL169 :"H:\Project\SG_Project\VHDL\SG\SG_WBM_IF.vhd":163:2:163:3|M
@W: CL190 :"H:\Project\SG_Project\VHDL\SG\SG_WBM_IF.vhd":163:2:163:3|M
@N: CL201 :"H:\Project\SG_Project\VHDL\SG\SG_WBM_IF.vhd":163:2:163:3|M
@W: CL260 :"H:\Project\SG_Project\VHDL\SG\SG_WBM_IF.vhd":163:2:163:3|M
@N: CD364 :"H:\Project\SG_Project\VHDL\SG\SG_WBM_IF.vhd":240:6:240:11|M
@N: CD364 :"H:\Project\SG_Project\VHDL\SG\SG_WBM_IF.vhd":281:6:281:11|M
@N: CD364 :"H:\Project\SG_Project\VHDL\SG\SG_WBM_IF.vhd":360:6:360:11|M
@TM:1366016762
@N:  :"h:\project\sg_project\vhdl\sg\sg_wbm_if.vhd":391:2:391:3|M
@TM:1366016634
@N: CD364 :"H:\Project\SG_Project\VHDL\SG\SG_WBM_IF.vhd":401:5:401:11|M
@N: CD364 :"H:\Project\SG_Project\VHDL\SG\SG_WBM_IF.vhd":404:4:404:10|M
@N: CD630 :"H:\Project\SG_Project\VHDL\SG\Symbol_Generator_Top.vhd":23:7:23:26|M
@W: CD638 :"H:\Project\SG_Project\VHDL\SG\Symbol_Generator_Top.vhd":208:8:208:22|M
@W: CD638 :"H:\Project\SG_Project\VHDL\SG\Symbol_Generator_Top.vhd":239:8:239:19|M
@W: CD638 :"H:\Project\SG_Project\VHDL\SG\Symbol_Generator_Top.vhd":240:8:240:19|M
@N: CD630 :"H:\Project\SG_Project\VHDL\sync_rst_gen.vhd":22:7:22:18|M
@N: CD630 :"H:\Project\SG_Project\VHDL\synthetic_frame_generator.vhd":25:7:25:31|M
@TM:1366016762
@W: BN132 :"h:\project\sg_project\vhdl\synthetic_frame_generator.vhd":107:2:107:3|M
@W: BN132 :"h:\project\sg_project\vhdl\synthetic_frame_generator.vhd":107:2:107:3|M
@W: BN132 :"h:\project\sg_project\vhdl\synthetic_frame_generator.vhd":107:2:107:3|M
@W: BN132 :"h:\project\sg_project\vhdl\synthetic_frame_generator.vhd":107:2:107:3|M
@TM:1366016634
@W: CL190 :"H:\Project\SG_Project\VHDL\synthetic_frame_generator.vhd":107:2:107:3|M
@N: CL201 :"H:\Project\SG_Project\VHDL\synthetic_frame_generator.vhd":107:2:107:3|M
@W: CL260 :"H:\Project\SG_Project\VHDL\synthetic_frame_generator.vhd":107:2:107:3|M
@W: CL260 :"H:\Project\SG_Project\VHDL\synthetic_frame_generator.vhd":107:2:107:3|M
@TM:1366016762
@W: MO161 :"h:\project\sg_project\vhdl\synthetic_frame_generator.vhd":107:2:107:3|M
@TM:1366016634
@N: CD364 :"H:\Project\SG_Project\VHDL\synthetic_frame_generator.vhd":154:4:154:14|M
@TM:1366016762
@N:  :"h:\project\sg_project\vhdl\synthetic_frame_generator.vhd":166:2:166:3|M
@N:  :"h:\project\sg_project\vhdl\synthetic_frame_generator.vhd":166:2:166:3|M
@TM:1366016634
@N: CD364 :"H:\Project\SG_Project\VHDL\synthetic_frame_generator.vhd":184:6:184:9|M
@N: CD364 :"H:\Project\SG_Project\VHDL\synthetic_frame_generator.vhd":185:6:185:9|M
@N: CD364 :"H:\Project\SG_Project\VHDL\synthetic_frame_generator.vhd":192:5:192:8|M
@N: CD364 :"H:\Project\SG_Project\VHDL\synthetic_frame_generator.vhd":193:5:193:8|M
@N:  :"H:\Project\SG_Project\VHDL\top_synthesis.vhd":23:7:23:19|M
@N: CD630 :"H:\Project\SG_Project\VHDL\top_synthesis.vhd":23:7:23:19|M
@W: CD638 :"H:\Project\SG_Project\VHDL\top_synthesis.vhd":213:7:213:28|M
@W: CD638 :"H:\Project\SG_Project\VHDL\top_synthesis.vhd":214:7:214:23|M
@N: CD630 :"H:\Project\SG_Project\VHDL\tx_path.vhd":25:7:25:13|M
@W: CL246 :"H:\Project\SG_Project\VHDL\tx_path.vhd":90:4:90:12|M
@W: CL159 :"H:\Project\SG_Project\VHDL\tx_path.vhd":91:4:91:12|M
@W: CD326 :"H:\Project\SG_Project\VHDL\tx_path.vhd":624:1:624:10|M
@N: CD630 :"H:\Project\SG_Project\VHDL\tx_path_wbm.vhd":25:7:25:17|M
@N: CD233 :"H:\Project\SG_Project\VHDL\tx_path_wbm.vhd":69:17:69:18|M
@TM:1366016762
@N:  :"h:\project\sg_project\vhdl\tx_path_wbm.vhd":134:2:134:3|M
@N:  :"h:\project\sg_project\vhdl\tx_path_wbm.vhd":134:2:134:3|M
@N: BN116 :"h:\project\sg_project\vhdl\tx_path_wbm.vhd":134:2:134:3|M
@TM:1366016634
@N: CL201 :"H:\Project\SG_Project\VHDL\tx_path_wbm.vhd":134:2:134:3|M
@N: CD364 :"H:\Project\SG_Project\VHDL\tx_path_wbm.vhd":170:6:170:16|M
@N: CD364 :"H:\Project\SG_Project\VHDL\tx_path_wbm.vhd":181:6:181:16|M
@N: CD364 :"H:\Project\SG_Project\VHDL\tx_path_wbm.vhd":182:6:182:18|M
@N: CD364 :"H:\Project\SG_Project\VHDL\tx_path_wbm.vhd":194:7:194:17|M
@N: CD364 :"H:\Project\SG_Project\VHDL\tx_path_wbm.vhd":195:7:195:19|M
@N: CD364 :"H:\Project\SG_Project\VHDL\tx_path_wbm.vhd":196:7:196:20|M
@N: CD364 :"H:\Project\SG_Project\VHDL\tx_path_wbm.vhd":202:5:202:15|M
@N: CD364 :"H:\Project\SG_Project\VHDL\tx_path_wbm.vhd":203:5:203:17|M
@N: CD364 :"H:\Project\SG_Project\VHDL\tx_path_wbm.vhd":204:5:204:18|M
@W: CD604 :"H:\Project\SG_Project\VHDL\tx_path_wbm.vhd":221:4:221:17|M
@N: CD364 :"H:\Project\SG_Project\VHDL\tx_path_wbm.vhd":249:4:249:12|M
@N: CD364 :"H:\Project\SG_Project\VHDL\tx_path_wbm.vhd":251:4:251:17|M
@N: CD364 :"H:\Project\SG_Project\VHDL\tx_path_wbm.vhd":263:4:263:12|M
@N: CD364 :"H:\Project\SG_Project\VHDL\tx_path_wbm.vhd":265:4:265:17|M
@N: CD630 :"H:\Project\SG_Project\VHDL\uart_rx.vhd":46:7:46:13|M
@N: CD231 :"H:\Project\SG_Project\VHDL\uart_rx.vhd":74:24:74:25|M
@TM:1366016762
@N:  :"h:\project\sg_project\vhdl\uart_rx.vhd":119:2:119:3|M
@TM:1366016634
@W: CL169 :"H:\Project\SG_Project\VHDL\uart_rx.vhd":119:2:119:3|M
@W: CL169 :"H:\Project\SG_Project\VHDL\uart_rx.vhd":119:2:119:3|M
@W: CL190 :"H:\Project\SG_Project\VHDL\uart_rx.vhd":119:2:119:3|M
@W: CL190 :"H:\Project\SG_Project\VHDL\uart_rx.vhd":119:2:119:3|M
@N: CL201 :"H:\Project\SG_Project\VHDL\uart_rx.vhd":119:2:119:3|M
@N: CD364 :"H:\Project\SG_Project\VHDL\uart_rx.vhd":162:8:162:17|M
@N: CD364 :"H:\Project\SG_Project\VHDL\uart_rx.vhd":231:7:231:16|M
@W: CD604 :"H:\Project\SG_Project\VHDL\uart_rx.vhd":302:4:302:17|M
@N: CD630 :"H:\Project\SG_Project\VHDL\uart_tx.vhd":39:7:39:13|M
@N: CD233 :"H:\Project\SG_Project\VHDL\uart_tx.vhd":70:24:70:25|M
@TM:1366016762
@N:  :"h:\project\sg_project\vhdl\uart_tx.vhd":111:2:111:3|M
@TM:1366016634
@N: CL201 :"H:\Project\SG_Project\VHDL\uart_tx.vhd":111:2:111:3|M
@N: CD364 :"H:\Project\SG_Project\VHDL\uart_tx.vhd":157:7:157:13|M
@W: CD604 :"H:\Project\SG_Project\VHDL\uart_tx.vhd":162:5:162:18|M
@N: CD630 :"H:\Project\SG_Project\VHDL\vesa_gen_ctrl.vhd":75:7:75:19|M
@TM:1366016762
@W: BN132 :"h:\project\sg_project\vhdl\vesa_gen_ctrl.vhd":255:2:255:3|M
@W: BN132 :"h:\project\sg_project\vhdl\vesa_gen_ctrl.vhd":255:2:255:3|M
@W: MO161 :"h:\project\sg_project\vhdl\vesa_gen_ctrl.vhd":255:2:255:3|M
@W: MO161 :"h:\project\sg_project\vhdl\vesa_gen_ctrl.vhd":255:2:255:3|M
@TM:1366016634
@N: CD364 :"H:\Project\SG_Project\VHDL\vesa_gen_ctrl.vhd":279:5:279:17|M
@N: CD364 :"H:\Project\SG_Project\VHDL\vesa_gen_ctrl.vhd":280:5:280:13|M
@N: CD364 :"H:\Project\SG_Project\VHDL\vesa_gen_ctrl.vhd":281:5:281:16|M
@N: CD364 :"H:\Project\SG_Project\VHDL\vesa_gen_ctrl.vhd":282:5:282:17|M
@N: CD364 :"H:\Project\SG_Project\VHDL\vesa_gen_ctrl.vhd":283:5:283:17|M
@N: CD364 :"H:\Project\SG_Project\VHDL\vesa_gen_ctrl.vhd":284:5:284:17|M
@TM:1366016762
@N: BN116 :"h:\project\sg_project\vhdl\vesa_gen_ctrl.vhd":307:2:307:3|M
@TM:1366016634
@N: CD364 :"H:\Project\SG_Project\VHDL\vesa_gen_ctrl.vhd":325:5:325:17|M
@N: CD364 :"H:\Project\SG_Project\VHDL\vesa_gen_ctrl.vhd":329:4:329:16|M
@N: CD630 :"H:\Project\SG_Project\VHDL\wbs_reg.vhd":26:7:26:13|M
@N: CD630 :"H:\Project\SG_Project\VHDL\wbs_reg.vhd":26:7:26:13|M
@W: CL159 :"H:\Project\SG_Project\VHDL\wbs_reg.vhd":33:3:33:5|M
@W: CL159 :"H:\Project\SG_Project\VHDL\wbs_reg.vhd":33:3:33:5|M
@W: CL159 :"H:\Project\SG_Project\VHDL\wbs_reg.vhd":36:3:36:7|M
@W: CL159 :"H:\Project\SG_Project\VHDL\wbs_reg.vhd":36:3:36:7|M
